2023-07-02 23:15:58,327 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-07-02 23:16:02,328 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-07-03 01:13:21,662 django.request WARNING  Not Found: /
2023-07-03 01:15:21,720 django.request WARNING  Not Found: /api/docs
2023-07-03 01:15:21,841 django.request WARNING  Not Found: /favicon.ico
2023-07-03 01:15:25,868 django.request WARNING  Not Found: /api/docs/
2023-07-03 01:16:47,981 django.request WARNING  Not Found: /api/v5/docs/
2023-07-03 01:16:57,568 django.request WARNING  Not Found: /api/v5/
2023-07-03 01:17:17,070 django       ERROR    2 validation errors for NinjaResponseSchema
response -> message
  field required (type=value_error.missing)
response -> data
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/bidout-auction-v5/env/lib/python3.11/site-packages/ninja/operation.py", line 266, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/bidout-auction-v5/env/lib/python3.11/site-packages/ninja/operation.py", line 202, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/bidout-auction-v5/env/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 2 validation errors for NinjaResponseSchema
response -> message
  field required (type=value_error.missing)
response -> data
  field required (type=value_error.missing)
2023-07-03 01:17:17,078 django.request ERROR    Internal Server Error: /api/v5/general/site-detail
2023-07-03 01:18:58,252 django.request WARNING  Not Found: /api/v5/general/site-detail/
2023-07-03 01:21:10,899 django.request WARNING  Not Found: /api/v5/general/site-detail/
2023-07-03 01:37:54,789 django.request WARNING  Not Found: /api/v5/docs
2023-07-03 01:37:54,867 django.request WARNING  Not Found: /favicon.ico
2023-07-03 01:38:01,550 django.request WARNING  Not Found: /
2023-07-03 01:38:13,590 django.request WARNING  Not Found: /
2023-07-03 02:58:21,427 django.request WARNING  Unprocessable Entity: /api/v5/general/subscribe/
2023-07-03 02:58:57,549 django.request WARNING  Unprocessable Entity: /api/v5/general/subscribe/
2023-07-03 02:59:24,379 django.request WARNING  Unprocessable Entity: /api/v5/general/subscribe/
2023-07-03 02:59:38,644 django.request WARNING  Unprocessable Entity: /api/v5/general/subscribe/
